# Generated by Django 4.1.5 on 2023-06-26 02:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hrSystem.models.employees_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assurance_type', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=10, unique=True)),
                ('routing_number_bank', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(default=hrSystem.models.employees_models.from_100000000, unique=True, validators=[django.core.validators.MinValueValidator(100000000)])),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('email', models.EmailField(max_length=128)),
                ('cin', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Enter a valid CIN number', regex='[1-9][0-9]{9}')])),
                ('nif', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid NIF number', regex='[0]{2}[1-9]-[0-9]{3}-[0-9]{3}-[0-9]')])),
                ('phone1', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='[234][0-9]{3}-[0-9]{4}')])),
                ('phone2', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='[234][0-9]{3}-[0-9]{4}')])),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('bank_account', models.IntegerField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE')], max_length=11)),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.assurance')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.bank')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouvement_type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_name', models.CharField(max_length=10)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hrSystem.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code', regex='[1-9][0-9]{3}')])),
                ('city', models.CharField(max_length=128)),
                ('state_province', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hrSystem.country')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 25))])),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('SICK LEAVE', 'SICK LEAVE'), ('VACATION', 'VACATION'), ('MATERNITY', 'MATERNITY'), ('PATERNITY', 'PATERNITY'), ('OTHER', 'OTHER')], max_length=40)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('can_edit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hrSystem.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.service'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.status'),
        ),
        migrations.AddField(
            model_name='departement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='hrSystem.location'),
        ),
        migrations.AddField(
            model_name='departement',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='hrSystem.employee'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='hrSystem.region'),
        ),
    ]
