# Generated by Django 4.1.5 on 2023-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mode_paiement',
            field=models.CharField(choices=[('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE')], max_length=11),
        ),
    ]
