# Generated by Django 4.1.5 on 2023-06-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='region',
            new_name='region_id',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='assurance',
            new_name='assurance_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='bank',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='service',
            new_name='service_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='departement',
            new_name='departement_id',
        ),
    ]
