# Generated by Django 4.1.5 on 2023-06-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0003_alter_employee_email_alter_leave_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
