# Generated by Django 4.1.5 on 2023-01-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0003_alter_departement_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='manager_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='hrSystem.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.bank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrSystem.service'),
        ),
    ]
