# Generated by Django 4.1.5 on 2023-01-31 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0004_alter_departement_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cin',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Enter a valid CIN number', regex='[1-9][0-9]{9}')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nif',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid NIF number', regex='[0]{2}[1-9]-[0-9]{3}-[0-9]{3}-[0-9]')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone1',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='[234][0-9]{3}-[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='[234][0-9]{3}-[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code', regex='[1-9][0-9]{3}')]),
        ),
    ]
