# Generated by Django 4.1.5 on 2023-06-30 17:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrSystem', '0006_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mode_paiement',
            field=models.CharField(choices=[('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE')], default='CHEQUE', max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 30))]),
        ),
    ]
