# Generated by Django 4.1.5 on 2023-02-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0006_rename_description_country_country_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='description',
            new_name='region_name',
        ),
    ]
