# Generated by Django 4.1.5 on 2023-02-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0007_rename_description_region_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='description',
            new_name='departement_name',
        ),
    ]
