# Generated by Django 4.1.5 on 2023-07-14 00:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0007_alter_employee_mode_paiement_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid CIN number', regex='[1-9][0-9]{9}')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nif',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid NIF number', regex='[0]{2}[1-9]-[0-9]{3}-[0-9]{3}-[0-9]')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone1',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='[234][0-9]{3}-[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='[234][0-9]{3}-[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 13))]),
        ),
    ]
