# Generated by Django 4.1.5 on 2023-02-02 01:32

import django.core.validators
from django.db import migrations, models
import hrSystem.models.employees_models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0008_rename_description_departement_departement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employe_id',
            field=models.IntegerField(default=hrSystem.models.employees_models.from_100000000, unique=True, validators=[django.core.validators.MinValueValidator(100000000)]),
        ),
    ]
