# Generated by Django 4.1.5 on 2023-07-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0008_rename_employee_id_leave_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hrSystem.employee'),
        ),
    ]
