# Generated by Django 4.1.5 on 2023-02-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0009_remove_employee_salary_alter_employee_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
