# Generated by Django 4.1.5 on 2023-08-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0010_daysoff_alter_leave_start_date_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysoff',
            name='fiscal_year',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
