# Generated by Django 4.1.5 on 2023-02-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0010_alter_status_status_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='max_salary',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_salary',
        ),
    ]
