# Generated by Django 4.1.5 on 2023-02-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrSystem', '0012_rename_description_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('MASCULINE', 'MASCULINE'), ('FEMININE', 'FEMININE')], max_length=15, null=True),
        ),
    ]
